version: '3'

services:
  api:
    build: ./api
    image: 127.0.0.1:5001/api
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379
  web:
    build: ./www
    image: 127.0.0.1:5001/www
    ports:
      - "80:80"
    environment:
      - API_ENDPOINT=http://api:5000/upload
  redis:
    image: redis
networks:
  red:

